<?php

defined('LOGGER_PRIORITY_LEVEL_ERR') || define('LOGGER_PRIORITY_LEVEL_ERR', 0);
defined('LOGGER_PRIORITY_LEVEL_WARNING') || define('LOGGER_PRIORITY_LEVEL_WARNING', 1);
defined('LOGGER_PRIORITY_LEVEL_INFO') || define('LOGGER_PRIORITY_LEVEL_INFO', 2);
defined('LOGGER_PRIORITY_LEVEL_DEBUG') || define('LOGGER_PRIORITY_LEVEL_DEBUG', 3);
